### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by lucky-dreamer-nn** [iambabao/table2seq#1]
您好，这个table2seq的数据集您可以提供一下下载链接吗？

**Comment by iambabao** [comment]
谢谢您的关注。当时使用的数据是[WIKIBIO数据集](https://aclanthology.org/D16-1128.pdf)，复现的应该是这篇文章[Towards Comprehensive Description Generation from Factual Attribute-value Tables](https://aclanthology.org/P19-1600)。因为时间有些久远，一些细节可能不是很完善。
